src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Unique
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Choice({"F", "M"})
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("DateTime")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Country
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, mappedBy="auteurs")
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }
    public function __toString(){
        return $this->nom_prenom;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->addAuteur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAuteur($this);
        }

        return $this;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/97[89][- ]?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9]$/")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("DateTime")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     * min = 0,
     * max = 20, 
     * notInRangeMessage = "Must be between {{ min }} and {{ max }} ")
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, inversedBy="livres")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     */
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }
    public function __toString(){
        return $this->titre;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        $this->auteurs->removeElement($auteur);

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn')
            ->add('titre')
            ->add('nombre_pages')
            ->add('date_de_parution')
            ->add('note')
            ->add('auteurs')
            ->add('genres')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\GenreRepository;
use App\Repository\LivreRepository;
use App\Repository\AuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class LivreController extends AbstractController
{
    /**
     * @Route("/", name="livre_index", methods={"GET"})
     */
    public function index(LivreRepository $livreRepository, GenreRepository $genreRepository, AuteurRepository $auteurRepository): Response
    {
        $livres = $livreRepository->findAll();

        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
            'genres' => $genreRepository->findAll(),
            'auteurs' => $auteurRepository->findAll(),
            'dates' => $livreRepository->findDates(),
        ]);
    }

    /**
     * @Route("/livre/new", name="livre_new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/livre/{id}", name="livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/livre/{id}/edit", name="livre_edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/livre/{id}", name="livre_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("/livre/chercher/{motCle}", name="livre_chercher", methods={"GET"})
     */
    public function chercher(String $motCle, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->findByTitre($motCle);

        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/livre/liste-entre-deux-dates/{dateMin}/{dateMax}")
     */
    public function listeEntreDeuxDates($dateMin, $dateMax, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->findBetweenTwoDates(strval($dateMin), strval($dateMax));
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/livre/liste-par-note/{note}", name="livre_list_by_note", methods={"GET"})
     */
    public function listByNote(LivreRepository $livreRepository, $note): Response
    {
        $livres = $livreRepository->findByNote($note);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/livre/liste-par-date/{date}/", name="livre_list_by_date", methods={"GET"})
     */
    public function listByDate(LivreRepository $livreRepository, $date): Response
    {
        $livres = $livreRepository->findByDate($date);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/livre/liste-par-auteur/{auteur}/", name="livre_list_by_auteur", methods={"GET"})
     */
    public function listByAuteur(LivreRepository $livreRepository, $auteur): Response
    {
        $livres = $livreRepository->findByAuteur($auteur);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/livre/liste-par-genre/{genre}/", name="livre_list_by_genre", methods={"GET"})
     */
    public function listByGenre(LivreRepository $livreRepository, $genre): Response
    {
        $livres =  $livreRepository->findByGenre($genre);

        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('vous etes sur ??');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
	<button class="btn btn-primary">Supprimer</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifer Livre{% endblock %}

{% block body %}
    <h1>Modifer Livre</h1>

    {{ include('livre/_form.html.twig', {'button_label': 'Modifer'}) }}
    {{ include('livre/_delete_form.html.twig') }}
    <a href="{{ path('livre_index') }}">Revenir a la liste</a>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres
{% endblock %}

{% block body %}
	<h1>Livres</h1>
	<form method="POST" onsubmit="chercher(event)">
		<span>Chercher</span>
		<input id="motCle" type="text" class="form-control">
		<button class="btn btn-primary my-2">Chercher</button>
	</form>

	<form method="POST" onsubmit="list(event)">
		<span>Lister les livres dont la date de parution est comprise entre deux années données
		</span>
		<input id="dateMin" type="number" class="form-control">
		<input id="dateMax" type="number" class="form-control">
		<button class="btn btn-primary my-2">Lister</button>
	</form>

	<span>Filter selon</span>
	<select class="form-select mt-2" onchange="filtrerParNote(event)">
		<option selected>Note</option>
		{% for i in 0..20 %}
			<option value="{{ i }}">{{ i }}</option>
		{% endfor %}
	</select>
	<select class="form-select mt-2" onchange="filtrerParDate(event)">
		<option selected>Date de publication</option>
		{% for date in dates|sort  %}
			<option value="{{date.date_de_parution|date("m/d/Y")}}">{{date.date_de_parution|date("m/d/Y")}}</option>
		{% endfor %}
	</select>
	<select class="form-select mt-2" onchange="filtrerParAuteur(event)">
		<option selected>Auteur</option>
		{% for auteur in auteurs %}
			<option value="{{auteur.id}}">{{auteur.nomPrenom}}</option>
		{% endfor %}
	</select>
	<select class="form-select mt-2" onchange="filtrerParGenre(event)">
		<option selected>Genre</option>
		{% for genre in genres %}
			<option value="{{genre.id}}">{{genre.nom}}</option>
		{% endfor %}
	</select>
	<table id="livres" class="table mt-5">
		<thead>
			<tr>
				<th>Isbn</th>
				<th>Titre</th>
				<th>Nombre de pages</th>
				<th>Date de parution</th>
				<th>Note</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for livre in livres %}
				<tr>
					<td>{{ livre.isbn }}</td>
					<td>{{ livre.titre }}</td>
					<td>{{ livre.nombrePages }}</td>
					<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>

					<td>
						<span id="livre-note-{{ livre.id }}">{{ livre.note }}</span>
					</td>


					<td>
						<a class="btn btn-primary" href="{{ path('livre_show', {'id': livre.id}) }}">Afficher</a>
						{% if is_granted('ROLE_ADMIN') %}
							<a class="btn btn-primary" href="{{ path('livre_edit', {'id': livre.id}) }}">Modifier</a>
							{{ include('livre/_delete_form.html.twig') }}
						{% endif %}
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="7">Aucun résultat</td>
				</tr>
			{% endfor %}

		</tbody>
	</table>
	{% if is_granted('ROLE_ADMIN') %}
		<a class="btn btn-primary" href="{{ path('livre_new') }}">Ajouter</a>
	{% endif %}
{% endblock %}
{% block javascripts %}
	<script src="/js/main.js"></script>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}creer Livre{% endblock %}

{% block body %}
    <h1>Creer un nouveau livre</h1>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('livre_index') }}">Revenir a la liste</a>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
    <h1>Livre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ livre.id }}</td>
            </tr>
            <tr>
                <th>Isbn</th>
                <td>{{ livre.isbn }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ livre.titre }}</td>
            </tr>
            <tr>
                <th>Nombre_pages</th>
                <td>{{ livre.nombrePages }}</td>
            </tr>
            <tr>
                <th>Date_de_parution</th>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ livre.note }}</td>
            </tr>
        </tbody>
    </table>
    {{ include('livre/_delete_form.html.twig') }}
    <a href="{{ path('livre_index') }}">Revenir a la liste</a>
    <a href="{{ path('livre_edit', {'id': livre.id}) }}">Modifier</a>

{% endblock %}